[tool.poetry]
name = "wikiwwii"
version = "0.1.0"
description = ""
authors = ["da griq <dagriq@yahoo.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
